### ISSUE TITLE
Sorastreamitaliano isn't working 

### ISSUE THREAD

**Issue by Destro9000** [Gian-Fr/ItalianProvider#1]
Hey gian , i was watching an episode of house of dragons from the sorastream provider and it was working fine , few hours later i wanted to keep eatching and now it gives me the link not found error , any help on fixing this?

**Comment by Gian-Fr** [comment]
Forse hai cambiato rete oppure il provider non era disponibile, sorastream ,come indicato nel readme, non garantisce che i contenuti siano reperibili
