### ISSUE TITLE
Problema nello scegliere i provider

### ISSUE THREAD

**Issue by black00019** [Gian-Fr/ItalianProvider#7]
Ho installato la repo in cloudstream, scaricando tutti i vari provider, ma quando vanno nella home per scegliere il provider mi visualizza solo SoraStreamItaliano

**Comment by Gian-Fr** [comment]
Ciao! 
Questo è il comportamento voluto, il solo provider per la home è SoraStreamItaliano, in quanto unico provider completo di informazioni

**Comment by black00019** [comment]
Scusa ma allora il README a cosa serve? visto che sono indicati anche altri providers?

**Comment by Gian-Fr** [comment]
Sorastream è l'unico provider per la home, i provider nel README sono quelli utilizzabili nella ricerca e visione, spero di essere stato chiaro

**Comment by black00019** [comment]
ok grazie
