### ISSUE TITLE
problem with calciostreaming provider

### ISSUE THREAD

**Issue by giannic79** [Gian-Fr/ItalianProvider#8]
ciao,
ringraziandoti per il tuo lavoro, vorrei comunque segnalarti un problema:
non vengono caricati i flussi video, viene visualizzato il messaggio link non trovato.
grazie

hello,
thanking you for your work, I would still like to report a problem:
the video streams are not loading, the message link not found is displayed.
thanks

**Comment by Gian-Fr** [comment]
Ciao, questo provider si occuperà di fornire SerieTv e Film, in quanto ho scoperto il nuovo repo [doGiorsHadEnough](https://github.com/doGior/doGiorsHadEnough) dove è già presente CalcioStreaming funzionante.

**Comment by giannic79** [comment]
Ciao Gian-Fr, grazie per la dritta... ho provato [doGiorsHadEnough](https://github.com/doGior/doGiorsHadEnough) ma niente da fare nn mi apre i links di calciostreaming

**Comment by Gian-Fr** [comment]
Assicurati di disattivare quello del mio repo, io l'ho provato personalmente e sembra funzionare

**Comment by giannic79** [comment]
grandeeee ha funzionato!!!! grazie 1000
