### ISSUE TITLE
problem with sorastream provider

### ISSUE THREAD

**Issue by giannic79** [Gian-Fr/ItalianProvider#9]
ciao,
ringraziandoti per il tuo lavoro, vorrei comunque segnalarti un problema riguardante la categoria serie tv:
non vengono caricati i flussi video, viene visualizzato il messaggio link non trovato.
grazie

hello,
thanking you for your work, I would still like to report a problem regarding the TV series category:
the video streams are not loaded, the message link not found is displayed.
thanks

**Comment by Gian-Fr** [comment]
Ciao, così come indicato nel readme sorastream funziona prevalentemente per i film, è in corso un refactor affinchè funzioni bene anche con le serie tv, però questo comporta l' aggiornamento dei provider che sta avvenendo gradualmente, nel momento in cui sarà pronto verranno disattivati tutti i singoli provider a favore di uno unificato
